apiVersion: apps/v1
kind: Deployment
metadata:
  name: netcore-prom-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netcore-prom-app
  template:
    metadata:
      labels:
        app: netcore-prom-app
    spec:
      containers:
      - name: netcore-prom-app
        image: erwinstaal/netcoreprom:1.1
        ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: netcore-prom-app-service
  labels:
    run: netcore-prom-app-service
spec:
  ports:
  - port: 8080
    targetPort: 80
    protocol: TCP
  selector:
    app: netcore-prom-app
---
apiVersion: v1
kind: Service
metadata:
  name: netcore-prom-app-external
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 31949
    name: http
  selector:
    app: netcore-prom-app