data:
  AzureWebJobsStorage: <storage-connection-string> # run func kubernetes deploy --name hello-keda --registry <dockerID> --dry-run > deploy.yaml to recreate
  FUNCTIONS_WORKER_RUNTIME: ZG90bmV0
apiVersion: v1
kind: Secret
metadata:
  name: hello-keda-queue
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-keda-queue
  namespace: default
  labels:
    app: hello-keda-queue
spec:
  selector:
    matchLabels:
      app: hello-keda-queue
  template:
    metadata:
      labels:
        app: hello-keda-queue
    spec:
      containers:
      - name: hello-keda-queue
        image: erwinstaal/hello-keda-queue
        env:
        - name: AzureFunctionsJobHost__functions__0
          value: hello_keda_queue
        envFrom:
        - secretRef:
            name: hello-keda-queue
      tolerations:
      - operator: Exists
---
apiVersion: keda.k8s.io/v1alpha1
kind: ScaledObject
metadata:
  name: hello-keda-queue
  namespace: default
  labels:
    deploymentName: hello-keda-queue
spec:
  scaleTargetRef:
    deploymentName: hello-keda-queue
  pollingInterval: 5 # Optional. Default: 30 seconds
  cooldownPeriod: 5 # Optional. Default: 300 seconds
  minReplicaCount: 0 # Optional. Default: 0
  maxReplicaCount: 20 # Optional. Default: 100
  triggers:
  - type: azure-queue
    metadata:
      type: queueTrigger
      connection: AzureWebJobsStorage
      queueName: myqueue-items
      name: myQueueItem
---

